import { CalendarDays, ChevronLeft, Download, Edit3, Mail, MapPin, PenTool, Share2, UserRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Button, StatusBadge } from '../components/ui';
import { SignaturePad } from '../components/SignaturePad';
import { authHeaders, jsonHeaders } from '../data/api';
import { reports } from '../data/repository';
import type { ReporteServicio, TimelineEvento } from '../domain/types';
import { useApp } from '../store/app';

export function Detail() { const { id = '' } = useParams(); const nav = useNavigate(); const notify = useApp(s=>s.notify); const [rs,setRs]=useState<ReporteServicio|null>(null); const [timeline,setTimeline]=useState<TimelineEvento[]>([]); const [sign,setSign]=useState(false); const [sending,setSending]=useState(false); useEffect(()=>{ void Promise.all([reports.get(id),reports.timeline(id)]).then(([r,t])=>{setRs(r);setTimeline(t)});},[id]); if(!rs)return <div className="loading">Cargando reporte…</div>;
  const share = async () => { const data={title:rs.id,text:`Reporte de servicio ${rs.id} - ${rs.cliente}`,url:location.href}; if(navigator.share) await navigator.share(data); else { await navigator.clipboard.writeText(location.href); notify('Enlace copiado'); } };
  const saveSignature = async (firma: ReporteServicio['firma']) => { const updated={...rs,firma}; await reports.saveDraft(updated); if(updated.estado !== 'Firmado' && ['Pendiente de firma','Finalizado sin firma'].includes(updated.estado)) { const transitioned=await reports.transition(updated.id,'Firmado'); setRs({...transitioned,firma}); } else setRs(updated); setSign(false); notify('Firma guardada'); };
  const sendToSlack = async () => { setSending(true); try { const pdf = await fetch(`/api/reportes/${rs.id}/pdf`, { method: 'POST', headers: authHeaders() }); if (!pdf.ok) throw new Error('No se pudo generar PDF'); const pdfData = await pdf.json() as { key: string }; const destino = rs.correo || rs.contacto || 'slack'; const delivery = await fetch(`/api/reportes/${rs.id}/enviar`, { method: 'POST', headers: jsonHeaders(), body: JSON.stringify({ destinatario: destino, pdfKey: pdfData.key }) }); if (!delivery.ok) throw new Error('No se pudo enviar a n8n'); notify('PDF enviado a n8n para Slack'); } catch (err) { notify(err instanceof Error ? err.message : 'Error enviando PDF'); } finally { setSending(false); } };
  return <div className="page detail"><button className="back" onClick={()=>nav(-1)}><ChevronLeft/> Volver</button><header><div><h1>{rs.id}</h1><p>{rs.cliente}</p></div><StatusBadge estado={rs.estado}/></header>{!rs.firma && ['Pendiente de firma','Finalizado sin firma'].includes(rs.estado) && <section className="detail-section"><h2>Esperando firma del cliente</h2><p>Abra la captura de firma, pida al cliente que firme en pantalla y guarde. El RS pasará a Firmado.</p><Button onClick={()=>setSign(true)}><PenTool/> Firmar ahora</Button></section>}<div className="detail-grid"><div><CalendarDays/><span>Fecha</span><strong>{rs.fecha}</strong></div><div><Edit3/><span>Tipo</span><strong>{rs.tipoVisita}</strong></div><div><UserRound/><span>Supervisor</span><strong>{rs.supervisor}</strong></div><div><MapPin/><span>Ubicación</span><strong>{rs.ubicacion}</strong></div></div><section className="detail-section"><h2>Línea de tiempo</h2><ol className="timeline">{timeline.map((t,i)=><li key={t.id} className={i===timeline.length-1?'current':''}><i/><div><strong>{t.tipo.replaceAll('_',' ')}</strong><span>{t.actor} · {new Date(t.fecha).toLocaleString('es-HN')}</span></div></li>)}</ol></section><section className="detail-section"><h2>Trabajo realizado</h2><p>{rs.trabajoRealizado||'Sin descripción registrada.'}</p>{rs.observaciones&&<><h3>Observaciones</h3><p>{rs.observaciones}</p></>}</section><section className="detail-section"><h2>Equipos · {rs.equipos.length}</h2>{rs.equipos.map(e=><div className="line-item" key={e.id}><strong>{e.nombre}</strong><span>{e.marca} {e.modelo} · {e.serie}</span><p>{e.trabajoRealizado}</p></div>)}</section><section className="detail-section"><h2>Materiales · {rs.materiales.length}</h2>{rs.materiales.map(m=><div className="line-item" key={m.id}><strong>{m.producto}</strong><span>{m.cantidad} {m.unidad} · {m.uso}</span></div>)}</section><section className="detail-section"><h2>Firma del cliente</h2>{rs.firma?<div className="signature-view"><img src={rs.firma.trazo} alt={`Firma de ${rs.firma.nombre}`}/><strong>{rs.firma.nombre}</strong><span>{rs.firma.cargo} · {new Date(rs.firma.firmadaEn).toLocaleString('es-HN')}</span></div>:<Button onClick={()=>setSign(true)}><PenTool/> Capturar firma</Button>}</section><section className="pdf-preview"><img src="/tas-mark.png"/><span>REPORTE DE SERVICIO</span><h2>{rs.id}</h2><h3>{rs.cliente}</h3><p>{rs.trabajoRealizado}</p></section><div className="detail-actions"><Button variant="danger" onClick={()=>window.print()}><Download/> Imprimir PDF local</Button><Button variant="outline" onClick={share}><Share2/> Compartir</Button><Button variant="outline" disabled={sending} onClick={sendToSlack}><Mail/> {sending ? 'Enviando...' : 'Enviar a Slack'}</Button><Button variant="ghost" onClick={()=>nav(`/editar/${rs.id}`)}><Edit3/> Editar reporte</Button></div>{sign&&<SignaturePad onCancel={()=>setSign(false)} onSave={saveSignature}/>}</div> }
