import { Camera, Check, ChevronLeft, ChevronRight, Plus, Save, Trash2, Upload } from 'lucide-react';
import { useCallback, useEffect, useState, type ChangeEvent } from 'react';
import { useLocation, useNavigate, useParams } from 'react-router-dom';
import { Button, Field, Input, Select, Textarea } from '../components/ui';
import { SignaturePad } from '../components/SignaturePad';
import { authHeaders } from '../data/api';
import { reports } from '../data/repository';
import type { CategoriaFoto, ReporteServicio } from '../domain/types';
import { TIPOS_VISITA, uid } from '../domain/types';
import { useApp } from '../store/app';

const titles = ['Cliente y visita', 'Trabajo realizado', 'Equipos intervenidos', 'Materiales y repuestos', 'Personal participante', 'Evidencias', 'Revisión y firma'];
type OdooCliente = { id: number; nombre: string; contacto: string; correo: string; telefono: string; ubicacion: string; tipo: string };
type OdooPersona = { id: number; nombre: string; correo: string; telefono: string; puesto: string; departamento: string };
export function ReportForm() {
  const { id } = useParams(); const nav = useNavigate(); const location = useLocation(); const notify = useApp(s => s.notify); const reload = useApp(s => s.load); const user = useApp(s => s.user); const draftKey = id ?? new URLSearchParams(location.search).get('draft') ?? 'new'; const stepKey = `rs-draft-step-${draftKey}`; const [step, setStep] = useState(1); const [rs, setRs] = useState<ReporteServicio | null>(null); const [saving, setSaving] = useState(false); const [dirty, setDirty] = useState(false); const [sign, setSign] = useState(false); const [photoCategory, setPhotoCategory] = useState<CategoriaFoto>('Durante'); const [clientesOdoo, setClientesOdoo] = useState<OdooCliente[]>([]); const [personalOdoo, setPersonalOdoo] = useState<OdooPersona[]>([]); const [personalIndex, setPersonalIndex] = useState<number | null>(null);
  useEffect(() => { setRs(null); setDirty(false); setStep(id ? Number(localStorage.getItem(stepKey) ?? 1) : 1); void (async () => setRs(id ? await reports.get(id) : blankReport(user?.nombre ?? '')))(); }, [id, stepKey, user?.nombre]);
  useEffect(() => { localStorage.setItem(stepKey, String(step)); window.scrollTo({ top: 0, behavior: 'smooth' }); }, [step, stepKey]);
  useEffect(() => { const q = rs?.cliente?.trim() ?? ''; if (step !== 1 || q.length < 2) { setClientesOdoo([]); return; } const t = window.setTimeout(() => { void fetch(`/api/odoo/clientes?q=${encodeURIComponent(q)}`, { headers: authHeaders() }).then(r => r.ok ? r.json() : { items: [] }).then((d: { items: OdooCliente[] }) => setClientesOdoo(d.items ?? [])).catch(() => setClientesOdoo([])); }, 350); return () => window.clearTimeout(t); }, [rs?.cliente, step]);
  const patch = useCallback((p: Partial<ReporteServicio>) => { setDirty(true); setRs(x => x ? { ...x, ...p } : x); }, []);
  const field = (key: keyof ReporteServicio) => ({ value: String(rs?.[key] ?? ''), onChange: (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => patch({ [key]: e.target.value }) });
  const addEquipo = () => patch({ equipos: [...rs!.equipos, { id: uid(), nombre: '', marca: '', modelo: '', serie: '', ubicacion: '', estadoInicial: '', estadoFinal: '', trabajoRealizado: '', recomendacion: '' }] });
  const addMaterial = () => patch({ materiales: [...rs!.materiales, { id: uid(), producto: '', cantidad: '1', unidad: 'Unidad', uso: 'Utilizado' }] });
  const addPersonal = () => patch({ personal: [...rs!.personal, { id: uid(), nombre: '', rol: 'Técnico', horaEntrada: '', horaSalida: '', horas: '' }] });
  const applyCliente = (cliente: OdooCliente) => { patch({ cliente: cliente.nombre, contacto: cliente.contacto || rs?.contacto || '', correo: cliente.correo || rs?.correo || '', telefono: cliente.telefono || rs?.telefono || '', ubicacion: cliente.ubicacion || rs?.ubicacion || '', solicitadoPor: cliente.contacto || rs?.solicitadoPor || '' }); setClientesOdoo([]); };
  const searchPersonal = (q: string, index: number) => { setPersonalIndex(index); if (q.trim().length < 2) { setPersonalOdoo([]); return; } void fetch(`/api/odoo/personal?q=${encodeURIComponent(q)}`, { headers: authHeaders() }).then(r => r.ok ? r.json() : { items: [] }).then((d: { items: OdooPersona[] }) => setPersonalOdoo(d.items ?? [])).catch(() => setPersonalOdoo([])); };
  const applyPersonal = (persona: OdooPersona) => { if (personalIndex === null || !rs) return; patch({ personal: rs.personal.map((q, j) => j === personalIndex ? { ...q, nombre: persona.nombre, rol: persona.puesto.toLowerCase().includes('ingen') ? 'Ingeniero' : 'Técnico' } : q) }); setPersonalOdoo([]); setPersonalIndex(null); };
  const saveReport = async () => {
    if (!rs) return null;
    setSaving(true);
    try {
      const saved = rs.id ? (await reports.saveDraft(rs), rs) : await reports.createDraft(rs);
      setRs(saved);
      setDirty(false);
      notify('RS guardado');
      if (!id) nav(`/editar/${saved.id}`, { replace: true });
      await reload();
      return saved;
    } finally {
      setSaving(false);
    }
  };
  const upload = async (e: ChangeEvent<HTMLInputElement>) => { try { const saved = rs?.id ? rs : await saveReport(); if (!saved?.id) return notify('Guarde el RS antes de subir fotos'); for (const file of Array.from(e.target.files ?? [])) await reports.putEvidencia(saved.id, file, { categoria: photoCategory, descripcion: file.name }); setRs(await reports.get(saved.id)); e.target.value = ''; notify(`Evidencia ${photoCategory.toLowerCase()} guardada en R2`); } catch { notify('No se pudo guardar la evidencia'); } };
  const finalize = async () => { const saved = rs?.id ? rs : await saveReport(); if (!saved) return; if (!saved.firma) return setSign(true); if (saved.estado !== 'Firmado') await reports.transition(saved.id, 'Firmado'); notify('Reporte firmado y listo para generar PDF'); await reload(); nav(`/rs/${saved.id}`); };
  const saveAndFinalizeSignature = async (firma: ReporteServicio['firma']) => { if (!rs) return; const base = rs.id ? rs : await reports.createDraft(rs); const updated = { ...base, firma }; await reports.saveDraft(updated); const signed = await reports.transition(updated.id, 'Firmado'); setRs({ ...signed, firma }); setDirty(false); setSign(false); notify('Firma guardada y RS firmado'); await reload(); nav(`/rs/${updated.id}`); };
  if (!rs) return <div className="loading">Preparando borrador…</div>;
  return <div className="form-page"><header className="form-header"><button onClick={() => nav('/')}><ChevronLeft /> Salir</button><span className="autosave"><Check />{saving ? 'Guardando…' : dirty ? 'Cambios sin guardar' : rs.id ? 'Guardado' : 'Sin guardar'}</span><div><h1>{titles[step - 1]}</h1><span>{rs.id || 'Nuevo RS'} · Paso {step} de 7</span></div><div className="progress">{titles.map((_, i) => <i key={i} className={i < step ? 'done' : ''} />)}</div></header><div className="form-content">
    {step === 1 && <section className="form-grid"><Field label="Fecha" required><Input type="date" {...field('fecha')} /></Field><Field label="Cliente" required><Input placeholder="Nombre del cliente" {...field('cliente')} /></Field>{clientesOdoo.length > 0 && <div className="span-2 detail-section"><h2>Sugerencias de Odoo</h2>{clientesOdoo.map(c => <button className="report-card" type="button" key={c.id} onClick={() => applyCliente(c)}><strong>{c.nombre}</strong><span>{[c.contacto, c.correo, c.telefono, c.ubicacion].filter(Boolean).join(' · ')}</span></button>)}</div>}<Field label="Contacto"><Input {...field('contacto')} /></Field><Field label="Correo"><Input type="email" {...field('correo')} /></Field><Field label="Teléfono"><Input type="tel" {...field('telefono')} /></Field><Field label="Ubicación" required><Input {...field('ubicacion')} /></Field><Field label="Orden de trabajo"><Input {...field('ordenTrabajo')} /></Field><Field label="Solicitado por"><Input {...field('solicitadoPor')} /></Field><div className="span-2"><Field label="Tipo de visita"><div className="choice-chips">{TIPOS_VISITA.map(t => <button type="button" className={rs.tipoVisita === t ? 'active' : ''} onClick={() => patch({ tipoVisita: t })} key={t}>{t}</button>)}</div></Field></div><Field label="Hora de llegada"><Input type="time" {...field('horaLlegada')} /></Field><Field label="Hora de salida"><Input type="time" {...field('horaSalida')} /></Field></section>}
    {step === 2 && <section className="form-grid"><div className="span-2"><Field label="Descripción del trabajo realizado" required><Textarea rows={6} {...field('trabajoRealizado')} /></Field></div><div className="span-2"><Field label="Observaciones y hallazgos"><Textarea rows={4} {...field('observaciones')} /></Field></div><Field label="Estado actual"><Select {...field('estadoActual')}><option>Operativo</option><option>Operativo con observaciones</option><option>Fuera de servicio</option></Select></Field><Field label="¿Próxima visita requerida?"><Select value={rs.proximaVisita ? 'si' : 'no'} onChange={e => patch({ proximaVisita: e.target.value === 'si' })}><option value="no">No</option><option value="si">Sí</option></Select></Field><div className="span-2"><Field label="Recomendaciones"><Textarea {...field('recomendaciones')} /></Field></div><div className="span-2"><Field label="Acciones pendientes"><Textarea {...field('accionesPendientes')} /></Field></div>{rs.proximaVisita && <Field label="Fecha de seguimiento"><Input type="date" {...field('fechaSeguimiento')} /></Field>}</section>}
    {step === 3 && <Dynamic title="Equipo" addLabel="Agregar equipo" onAdd={addEquipo}>{rs.equipos.map((x, i) => <article className="dynamic-card" key={x.id}><button className="remove" onClick={() => patch({ equipos: rs.equipos.filter((_, j) => j !== i) })}><Trash2 /></button><div className="form-grid"><Field label="Nombre"><Input value={x.nombre} onChange={e => patch({ equipos: rs.equipos.map((q,j) => j===i?{...q,nombre:e.target.value}:q) })} /></Field><Field label="Marca y modelo"><Input value={`${x.marca}${x.modelo ? ` ${x.modelo}` : ''}`} onChange={e => patch({ equipos: rs.equipos.map((q,j) => j===i?{...q,marca:e.target.value}:q) })} /></Field><Field label="N° de serie"><Input value={x.serie} onChange={e => patch({ equipos: rs.equipos.map((q,j) => j===i?{...q,serie:e.target.value}:q) })} /></Field><Field label="Ubicación"><Input value={x.ubicacion} onChange={e => patch({ equipos: rs.equipos.map((q,j) => j===i?{...q,ubicacion:e.target.value}:q) })} /></Field><div className="span-2"><Field label="Trabajo realizado"><Textarea value={x.trabajoRealizado} onChange={e => patch({ equipos: rs.equipos.map((q,j) => j===i?{...q,trabajoRealizado:e.target.value}:q) })} /></Field></div></div></article>)}</Dynamic>}
    {step === 4 && <Dynamic title="Material" addLabel="Agregar material" onAdd={addMaterial}>{rs.materiales.map((x,i) => <article className="dynamic-card compact" key={x.id}><button className="remove" onClick={() => patch({ materiales: rs.materiales.filter((_,j)=>j!==i) })}><Trash2 /></button><div className="form-grid"><Field label="Producto"><Input value={x.producto} onChange={e => patch({ materiales: rs.materiales.map((q,j)=>j===i?{...q,producto:e.target.value}:q) })} /></Field><Field label="Cantidad"><Input value={x.cantidad} onChange={e => patch({ materiales: rs.materiales.map((q,j)=>j===i?{...q,cantidad:e.target.value}:q) })} /></Field><Field label="Unidad"><Input value={x.unidad} onChange={e => patch({ materiales: rs.materiales.map((q,j)=>j===i?{...q,unidad:e.target.value}:q) })} /></Field><Field label="Uso"><Select value={x.uso} onChange={e => patch({ materiales: rs.materiales.map((q,j)=>j===i?{...q,uso:e.target.value as typeof x.uso}:q) })}><option>Instalado</option><option>Utilizado</option><option>Entregado</option></Select></Field></div></article>)}</Dynamic>}
    {step === 5 && <Dynamic title="Participante" addLabel="Agregar participante" onAdd={addPersonal}>{rs.personal.map((x,i) => <article className="dynamic-card compact" key={x.id}><button className="remove" onClick={() => patch({ personal: rs.personal.filter((_,j)=>j!==i) })}><Trash2 /></button><div className="form-grid"><Field label="Nombre"><Input value={x.nombre} onChange={e => { patch({ personal: rs.personal.map((q,j)=>j===i?{...q,nombre:e.target.value}:q) }); searchPersonal(e.target.value, i); }} /></Field><Field label="Rol"><Select value={x.rol} onChange={e => patch({ personal: rs.personal.map((q,j)=>j===i?{...q,rol:e.target.value as typeof x.rol}:q) })}><option>Técnico</option><option>Ingeniero</option><option>Supervisor</option><option>Ayudante</option></Select></Field><Field label="Entrada"><Input type="time" value={x.horaEntrada} onChange={e => patch({ personal: rs.personal.map((q,j)=>j===i?{...q,horaEntrada:e.target.value}:q) })} /></Field><Field label="Salida"><Input type="time" value={x.horaSalida} onChange={e => patch({ personal: rs.personal.map((q,j)=>j===i?{...q,horaSalida:e.target.value}:q) })} /></Field></div>{personalIndex === i && personalOdoo.length > 0 && <div className="detail-section"><h2>Sugerencias de Odoo</h2>{personalOdoo.map(p => <button className="report-card" type="button" key={p.id} onClick={() => applyPersonal(p)}><strong>{p.nombre}</strong><span>{[p.puesto, p.departamento, p.correo].filter(Boolean).join(' · ')}</span></button>)}</div>}</article>)}</Dynamic>}
    {step === 6 && <section><Field label="Tipo de foto"><div className="choice-chips">{(['Antes','Durante','Después'] as CategoriaFoto[]).map(x => <button type="button" key={x} className={photoCategory === x ? 'active' : ''} onClick={() => setPhotoCategory(x)}>{x}</button>)}</div></Field><div className="upload-actions"><Button><Camera /> Capturar foto<input type="file" accept="image/*" capture="environment" onChange={upload} /></Button><Button variant="outline"><Upload /> Subir foto<input type="file" accept="image/*" multiple onChange={upload} /></Button></div><p className="evidence-count">{rs.evidencias.length} evidencias</p><div className="evidence-grid">{rs.evidencias.map(e => <article key={e.id}><Camera /><span>{e.categoria}</span><p>{e.descripcion}</p><button onClick={async () => { if (!rs.id) return; await reports.removeEvidencia(rs.id,e.id); setRs(await reports.get(rs.id)); }}><Trash2 /></button></article>)}</div></section>}
    {step === 7 && <section className="review"><div className="alert warning">Revise la información antes de capturar la firma y finalizar.</div><div className="review-card"><h2>{rs.cliente || 'Cliente pendiente'}</h2><p>{rs.tipoVisita} · {rs.fecha}</p><dl><div><dt>Trabajo</dt><dd>{rs.trabajoRealizado || 'Sin descripción'}</dd></div><div><dt>Equipos</dt><dd>{rs.equipos.length}</dd></div><div><dt>Materiales</dt><dd>{rs.materiales.length}</dd></div><div><dt>Fotos</dt><dd>{rs.evidencias.length}</dd></div></dl></div>{rs.firma ? <div className="signed"><Check /> Firmado por {rs.firma.nombre}</div> : <Button variant="outline" onClick={() => setSign(true)}>Capturar firma del cliente</Button>}<Button className="final-button" onClick={finalize}>Finalizar reporte</Button></section>}
  </div><footer className="form-footer"><Button variant="outline" disabled={step === 1} onClick={() => setStep(s => Math.max(1,s-1))}><ChevronLeft /> Atrás</Button>{step < 7 && <Button onClick={() => setStep(s => Math.min(7,s+1))}>Continuar <ChevronRight /></Button>}<Button variant="ghost" onClick={() => { void saveReport(); }}><Save /> Guardar</Button></footer>{sign && <SignaturePad onCancel={() => setSign(false)} onSave={saveAndFinalizeSignature} />}</div>;
}
function Dynamic({ children, title, addLabel, onAdd }: { children: React.ReactNode; title: string; addLabel: string; onAdd: () => void }) { return <section className="dynamic"><h2>{title}</h2>{children}<Button variant="outline" className="add-dashed" onClick={onAdd}><Plus /> {addLabel}</Button></section> }
function blankReport(nombre: string): ReporteServicio { const now = new Date().toISOString(); return { id: '', estado: 'Borrador', version: 1, fecha: now.slice(0, 10), cliente: '', contacto: '', correo: '', telefono: '', ubicacion: '', solicitadoPor: '', tipoVisita: 'Mantenimiento', horaLlegada: '', horaSalida: '', trabajoRealizado: '', observaciones: '', estadoActual: 'Operativo', recomendaciones: '', accionesPendientes: '', proximaVisita: false, equipos: [], materiales: [], personal: [], evidencias: [], supervisor: nombre, creadoPor: nombre, creadoEn: now, actualizadoEn: now }; }
