import { Camera, Check, ChevronLeft, ChevronRight, Plus, Save, Trash2, Upload } from 'lucide-react';
import { useCallback, useEffect, useRef, useState, type ChangeEvent } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Button, Field, Input, Select, Textarea } from '../components/ui';
import { SignaturePad } from '../components/SignaturePad';
import { reports } from '../data/repository';
import type { CategoriaFoto, ReporteServicio } from '../domain/types';
import { TIPOS_VISITA, uid } from '../domain/types';
import { useApp } from '../store/app';

const titles = ['Cliente y visita', 'Trabajo realizado', 'Equipos intervenidos', 'Materiales y repuestos', 'Personal participante', 'Evidencias', 'Revisión y firma'];
export function ReportForm() {
  const { id } = useParams(); const nav = useNavigate(); const notify = useApp(s => s.notify); const reload = useApp(s => s.load); const user = useApp(s => s.user); const [step, setStep] = useState(Number(localStorage.getItem('rs-draft-step') ?? 1)); const [rs, setRs] = useState<ReporteServicio | null>(null); const [saving, setSaving] = useState(false); const [sign, setSign] = useState(false); const timer = useRef<number>(0);
  useEffect(() => { void (async () => setRs(id ? await reports.get(id) : await reports.createDraft({ supervisor: user?.nombre, creadoPor: user?.nombre })))(); }, [id, user?.nombre]);
  useEffect(() => { if (!rs) return; window.clearTimeout(timer.current); setSaving(true); timer.current = window.setTimeout(() => { void reports.saveDraft(rs).then(() => setSaving(false)); }, 800); return () => window.clearTimeout(timer.current); }, [rs]);
  useEffect(() => { localStorage.setItem('rs-draft-step', String(step)); window.scrollTo({ top: 0, behavior: 'smooth' }); }, [step]);
  const patch = useCallback((p: Partial<ReporteServicio>) => setRs(x => x ? { ...x, ...p } : x), []);
  const field = (key: keyof ReporteServicio) => ({ value: String(rs?.[key] ?? ''), onChange: (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => patch({ [key]: e.target.value }) });
  const addEquipo = () => patch({ equipos: [...rs!.equipos, { id: uid(), nombre: '', marca: '', modelo: '', serie: '', ubicacion: '', estadoInicial: '', estadoFinal: '', trabajoRealizado: '', recomendacion: '' }] });
  const addMaterial = () => patch({ materiales: [...rs!.materiales, { id: uid(), producto: '', cantidad: '1', unidad: 'Unidad', uso: 'Utilizado' }] });
  const addPersonal = () => patch({ personal: [...rs!.personal, { id: uid(), nombre: '', rol: 'Técnico', horaEntrada: '', horaSalida: '', horas: '' }] });
  const upload = async (e: ChangeEvent<HTMLInputElement>, categoria: CategoriaFoto = 'Durante') => { try { for (const file of Array.from(e.target.files ?? [])) await reports.putEvidencia(rs!.id, file, { categoria, descripcion: file.name }); setRs(await reports.get(rs!.id)); notify('Evidencia guardada en R2'); } catch { notify('No se pudo guardar la evidencia'); } };
  const finalize = async () => { if (!rs?.firma) return setSign(true); const to = rs.estado === 'Borrador' ? 'Pendiente de firma' : rs.estado; if (to !== rs.estado) await reports.transition(rs.id, to); notify('Reporte firmado y listo para generar PDF'); await reload(); nav(`/rs/${rs.id}`); };
  if (!rs) return <div className="loading">Preparando borrador…</div>;
  return <div className="form-page"><header className="form-header"><button onClick={() => nav('/')}><ChevronLeft /> Salir</button><span className="autosave"><Check />{saving ? 'Guardando…' : 'Guardado automático'}</span><div><h1>{titles[step - 1]}</h1><span>Paso {step} de 7</span></div><div className="progress">{titles.map((_, i) => <i key={i} className={i < step ? 'done' : ''} />)}</div></header><div className="form-content">
    {step === 1 && <section className="form-grid"><Field label="Fecha" required><Input type="date" {...field('fecha')} /></Field><Field label="Cliente" required><Input placeholder="Nombre del cliente" {...field('cliente')} /></Field><Field label="Contacto"><Input {...field('contacto')} /></Field><Field label="Correo"><Input type="email" {...field('correo')} /></Field><Field label="Teléfono"><Input type="tel" {...field('telefono')} /></Field><Field label="Ubicación" required><Input {...field('ubicacion')} /></Field><Field label="Orden de trabajo"><Input {...field('ordenTrabajo')} /></Field><Field label="Solicitado por"><Input {...field('solicitadoPor')} /></Field><div className="span-2"><Field label="Tipo de visita"><div className="choice-chips">{TIPOS_VISITA.map(t => <button type="button" className={rs.tipoVisita === t ? 'active' : ''} onClick={() => patch({ tipoVisita: t })} key={t}>{t}</button>)}</div></Field></div><Field label="Hora de llegada"><Input type="time" {...field('horaLlegada')} /></Field><Field label="Hora de salida"><Input type="time" {...field('horaSalida')} /></Field></section>}
    {step === 2 && <section className="form-grid"><div className="span-2"><Field label="Descripción del trabajo realizado" required><Textarea rows={6} {...field('trabajoRealizado')} /></Field></div><div className="span-2"><Field label="Observaciones y hallazgos"><Textarea rows={4} {...field('observaciones')} /></Field></div><Field label="Estado actual"><Select {...field('estadoActual')}><option>Operativo</option><option>Operativo con observaciones</option><option>Fuera de servicio</option></Select></Field><Field label="¿Próxima visita requerida?"><Select value={rs.proximaVisita ? 'si' : 'no'} onChange={e => patch({ proximaVisita: e.target.value === 'si' })}><option value="no">No</option><option value="si">Sí</option></Select></Field><div className="span-2"><Field label="Recomendaciones"><Textarea {...field('recomendaciones')} /></Field></div><div className="span-2"><Field label="Acciones pendientes"><Textarea {...field('accionesPendientes')} /></Field></div>{rs.proximaVisita && <Field label="Fecha de seguimiento"><Input type="date" {...field('fechaSeguimiento')} /></Field>}</section>}
    {step === 3 && <Dynamic title="Equipo" addLabel="Agregar equipo" onAdd={addEquipo}>{rs.equipos.map((x, i) => <article className="dynamic-card" key={x.id}><button className="remove" onClick={() => patch({ equipos: rs.equipos.filter((_, j) => j !== i) })}><Trash2 /></button><div className="form-grid"><Field label="Nombre"><Input value={x.nombre} onChange={e => patch({ equipos: rs.equipos.map((q,j) => j===i?{...q,nombre:e.target.value}:q) })} /></Field><Field label="Marca y modelo"><Input value={`${x.marca}${x.modelo ? ` ${x.modelo}` : ''}`} onChange={e => patch({ equipos: rs.equipos.map((q,j) => j===i?{...q,marca:e.target.value}:q) })} /></Field><Field label="N° de serie"><Input value={x.serie} onChange={e => patch({ equipos: rs.equipos.map((q,j) => j===i?{...q,serie:e.target.value}:q) })} /></Field><Field label="Ubicación"><Input value={x.ubicacion} onChange={e => patch({ equipos: rs.equipos.map((q,j) => j===i?{...q,ubicacion:e.target.value}:q) })} /></Field><div className="span-2"><Field label="Trabajo realizado"><Textarea value={x.trabajoRealizado} onChange={e => patch({ equipos: rs.equipos.map((q,j) => j===i?{...q,trabajoRealizado:e.target.value}:q) })} /></Field></div></div></article>)}</Dynamic>}
    {step === 4 && <Dynamic title="Material" addLabel="Agregar material" onAdd={addMaterial}>{rs.materiales.map((x,i) => <article className="dynamic-card compact" key={x.id}><button className="remove" onClick={() => patch({ materiales: rs.materiales.filter((_,j)=>j!==i) })}><Trash2 /></button><div className="form-grid"><Field label="Producto"><Input value={x.producto} onChange={e => patch({ materiales: rs.materiales.map((q,j)=>j===i?{...q,producto:e.target.value}:q) })} /></Field><Field label="Cantidad"><Input value={x.cantidad} onChange={e => patch({ materiales: rs.materiales.map((q,j)=>j===i?{...q,cantidad:e.target.value}:q) })} /></Field><Field label="Unidad"><Input value={x.unidad} onChange={e => patch({ materiales: rs.materiales.map((q,j)=>j===i?{...q,unidad:e.target.value}:q) })} /></Field><Field label="Uso"><Select value={x.uso} onChange={e => patch({ materiales: rs.materiales.map((q,j)=>j===i?{...q,uso:e.target.value as typeof x.uso}:q) })}><option>Instalado</option><option>Utilizado</option><option>Entregado</option></Select></Field></div></article>)}</Dynamic>}
    {step === 5 && <Dynamic title="Participante" addLabel="Agregar participante" onAdd={addPersonal}>{rs.personal.map((x,i) => <article className="dynamic-card compact" key={x.id}><button className="remove" onClick={() => patch({ personal: rs.personal.filter((_,j)=>j!==i) })}><Trash2 /></button><div className="form-grid"><Field label="Nombre"><Input value={x.nombre} onChange={e => patch({ personal: rs.personal.map((q,j)=>j===i?{...q,nombre:e.target.value}:q) })} /></Field><Field label="Rol"><Select value={x.rol} onChange={e => patch({ personal: rs.personal.map((q,j)=>j===i?{...q,rol:e.target.value as typeof x.rol}:q) })}><option>Técnico</option><option>Ingeniero</option><option>Supervisor</option><option>Ayudante</option></Select></Field><Field label="Entrada"><Input type="time" value={x.horaEntrada} onChange={e => patch({ personal: rs.personal.map((q,j)=>j===i?{...q,horaEntrada:e.target.value}:q) })} /></Field><Field label="Salida"><Input type="time" value={x.horaSalida} onChange={e => patch({ personal: rs.personal.map((q,j)=>j===i?{...q,horaSalida:e.target.value}:q) })} /></Field></div></article>)}</Dynamic>}
    {step === 6 && <section><div className="upload-actions"><Button><Camera /> Capturar foto<input type="file" accept="image/*" capture="environment" onChange={upload} /></Button><Button variant="outline"><Upload /> Subir foto<input type="file" accept="image/*" multiple onChange={upload} /></Button></div><p className="evidence-count">{rs.evidencias.length} evidencias</p><div className="evidence-grid">{rs.evidencias.map(e => <article key={e.id}><Camera /><span>{e.categoria}</span><p>{e.descripcion}</p><button onClick={async () => { await reports.removeEvidencia(rs.id,e.id); setRs(await reports.get(rs.id)); }}><Trash2 /></button></article>)}</div></section>}
    {step === 7 && <section className="review"><div className="alert warning">Revise la información antes de capturar la firma y finalizar.</div><div className="review-card"><h2>{rs.cliente || 'Cliente pendiente'}</h2><p>{rs.tipoVisita} · {rs.fecha}</p><dl><div><dt>Trabajo</dt><dd>{rs.trabajoRealizado || 'Sin descripción'}</dd></div><div><dt>Equipos</dt><dd>{rs.equipos.length}</dd></div><div><dt>Materiales</dt><dd>{rs.materiales.length}</dd></div><div><dt>Fotos</dt><dd>{rs.evidencias.length}</dd></div></dl></div>{rs.firma ? <div className="signed"><Check /> Firmado por {rs.firma.nombre}</div> : <Button variant="outline" onClick={() => setSign(true)}>Capturar firma del cliente</Button>}<Button className="final-button" onClick={finalize}>Finalizar reporte</Button></section>}
  </div><footer className="form-footer"><Button variant="outline" disabled={step === 1} onClick={() => setStep(s => Math.max(1,s-1))}><ChevronLeft /> Atrás</Button>{step < 7 && <Button onClick={() => setStep(s => Math.min(7,s+1))}>Continuar <ChevronRight /></Button>}<Button variant="ghost" onClick={() => { void reports.saveDraft(rs); notify('Borrador guardado'); }}><Save /> Guardar</Button></footer>{sign && <SignaturePad onCancel={() => setSign(false)} onSave={firma => { patch({ firma }); setSign(false); notify('Firma capturada'); }} />}</div>;
}
function Dynamic({ children, title, addLabel, onAdd }: { children: React.ReactNode; title: string; addLabel: string; onAdd: () => void }) { return <section className="dynamic"><h2>{title}</h2>{children}<Button variant="outline" className="add-dashed" onClick={onAdd}><Plus /> {addLabel}</Button></section> }
